version: '3'
services:
  django_app:
    build:
      context: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_messenger_project
    ports:
      - "8000:8000"
    depends_on:
      - psql_db
      - redis

  psql_db:
    image: postgres
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: superuser
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  redis:
      image: redis
      ports:
        - "6379:6379"

  celery-beat:
    build: .
    command: celery -A django_messenger_project beat -l info
    volumes:
      - .:/django_messenger_project
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-worker:
    build: .
    command: celery -A django_messenger_project worker -l info
    volumes:
      - .:/django_messenger_project
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0